/**
 * A live response the MODULE composed from its own findings, two of whose references it attached: the
 * recorded allergies `[3]` (tiotropium) and `[1]` (lidocaine), each the chart record behind a cited
 * allergy finding, `[45]` and `[46]`, and each saying so in `attachedFor`.
 *
 * Patient `763e6e5f-c489-4bab-8a55-c379f085dd1c`, asked *"Does she have any drug interactions I should
 * know about?"*. Measured 2026-09-30 on an OpenMRS 3.7.1 standalone with the bundled DDInter knowledge
 * base, through `POST /chartsearchai/search` (question id 13090). Verbatim as the wire carried it, every
 * key included.
 */
export const SCREEN_WITH_ATTACHED_ALLERGY_RECORDS = {
  unstatedFindingSeverities: null,
  questionId: '13090',
  references: [
    {
      index: 3,
      resourceType: 'allergy',
      resourceUuid: '6b4652e6-c8d4-49ce-9096-e93693893cd2',
      date: null,
      grounded: null,
      group: 'chart',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: true,
      attachedFor: [45],
    },
    {
      index: 1,
      resourceType: 'allergy',
      resourceUuid: '2442c512-a43e-11f1-93d0-deb0bf1c9adc',
      date: null,
      grounded: null,
      group: 'chart',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: true,
      attachedFor: [46],
    },
    {
      index: 47,
      resourceType: 'safety_finding',
      resourceUuid: 'interaction:Botulinum toxin type A',
      date: null,
      grounded: null,
      group: 'reference',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: false,
      attachedFor: [],
    },
    {
      index: 48,
      resourceType: 'safety_finding',
      resourceUuid: 'interaction:Lidocaine',
      date: null,
      grounded: null,
      group: 'reference',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: false,
      attachedFor: [],
    },
    {
      index: 49,
      resourceType: 'safety_finding',
      resourceUuid: 'interaction:Lidocaine',
      date: null,
      grounded: null,
      group: 'reference',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: false,
      attachedFor: [],
    },
    {
      index: 45,
      resourceType: 'safety_finding',
      resourceUuid: 'contraindication:Tiotropium',
      date: null,
      grounded: null,
      group: 'reference',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: false,
      attachedFor: [],
    },
    {
      index: 46,
      resourceType: 'safety_finding',
      resourceUuid: 'contraindication:Lidocaine',
      date: null,
      grounded: null,
      group: 'reference',
      source: null,
      withheldInteractions: 0,
      attachedByTheModule: false,
      attachedFor: [],
    },
  ],
  activeOrderClaims: null,
  unresolvedDrugClass: null,
  findingPartners: null,
  unfoundedFindingSeverities: null,
  misattributedOrderCitations: null,
  interactionClaimPairs: null,
  answeredByTheModule: true,
  unfaithfullyRenderedCitations: null,
  cautionLedOverWithholding: null,
  chartReadForSafety: true,
  answer:
    'Botulinum toxin type A interacts with active order Neomycin — Major. The effects of botulinum toxin may be potentiated by neuromuscular blockers, aminoglycoside antibiotics, and other drugs that can interfere with neuromuscular transmission.  Botulinum toxin inhibits the release of acetylcholine from peripheral cholinergic nerve endings, thus additive neuromuscular blocking effects may occur when these agents are used together. [47]\nLidocaine interacts with active order Metoclopramide — Major. Coadministration of local anesthetics with other oxidizing agents that can also induce methemoglobinemia such as antimalarials (e.g., chloroquine, primaquine, quinine, tafenoquine), nitrates and nitrites, sulfonamides, aminosalicylic acid, dapsone, dimethyl sulfoxide, flutamide, metoclopramide, nitrofurantoin, phenazopyridine, phenobarbital, phenytoin, and rasburicase may increase the risk. [48]\nLidocaine interacts with active order Neomycin — Minor. Limited in vitro data suggest that some aminoglycosides may enhance the neuromuscular blocking properties of lidocaine. Data are available for neomycin only. No special precautions are necessary. [49]\nThe patient has a recorded allergy to Tiotropium. No severity is rated for this finding. This finding is about a medication this patient is already taking. [45]\nThe patient has a recorded allergy to Lidocaine. No severity is rated for this finding. This finding is about a medication this patient is already taking. [46]',
  findingCitations: null,
  interactionPairs: {
    found: 3,
    reported: 3,
    belowFloor: null,
  },
  conditionRuleCoverage: 'absent',
  orderStopDates: [],
  safetyWarnings: [
    {
      type: 'contraindication',
      drug: 'Tiotropium',
      detail: 'The patient has a recorded allergy to Tiotropium.',
      severity: null,
      chartOrderBridges: [],
      namedPartners: [],
      restsOnAnUncorroboratedChartMatch: false,
      aboutAnEndedOrder: false,
      endedOrderStopDate: null,
      aboutACurrentMedication: true,
      currentMedicationOrders: [
        {
          orderDisplay: 'Tiotropium',
          orderUuid: '238e9b4c-5dc2-4e7c-9089-0e439b9c15b8',
        },
      ],
      statedInTheAnswer: true,
    },
    {
      type: 'contraindication',
      drug: 'Lidocaine',
      detail: 'The patient has a recorded allergy to Lidocaine.',
      severity: null,
      chartOrderBridges: [],
      namedPartners: [],
      restsOnAnUncorroboratedChartMatch: false,
      aboutAnEndedOrder: false,
      endedOrderStopDate: null,
      aboutACurrentMedication: true,
      currentMedicationOrders: [
        {
          orderDisplay: 'Lidocaine',
          orderUuid: 'i1520000-0000-0000-0000-0000000000c2',
        },
      ],
      statedInTheAnswer: true,
    },
    {
      type: 'interaction',
      drug: 'Botulinum toxin type A',
      detail:
        'Botulinum toxin type A interacts with active order Neomycin — Major. The effects of botulinum toxin may be potentiated by neuromuscular blockers, aminoglycoside antibiotics, and other drugs that can interfere with neuromuscular transmission.  Botulinum toxin inhibits the release of acetylcholine from peripheral cholinergic nerve endings, thus additive neuromuscular blocking effects may occur when these agents are used together.',
      severity: 'Major',
      chartOrderBridges: [],
      namedPartners: ['Neomycin'],
      restsOnAnUncorroboratedChartMatch: false,
      aboutAnEndedOrder: false,
      endedOrderStopDate: null,
      aboutACurrentMedication: true,
      currentMedicationOrders: [],
      statedInTheAnswer: true,
    },
    {
      type: 'interaction',
      drug: 'Lidocaine',
      detail:
        'Lidocaine interacts with active order Metoclopramide — Major. Coadministration of local anesthetics with other oxidizing agents that can also induce methemoglobinemia such as antimalarials (e.g., chloroquine, primaquine, quinine, tafenoquine), nitrates and nitrites, sulfonamides, aminosalicylic acid, dapsone, dimethyl sulfoxide, flutamide, metoclopramide, nitrofurantoin, phenazopyridine, phenobarbital, phenytoin, and rasburicase may increase the risk.',
      severity: 'Major',
      chartOrderBridges: [],
      namedPartners: ['Metoclopramide'],
      restsOnAnUncorroboratedChartMatch: false,
      aboutAnEndedOrder: false,
      endedOrderStopDate: null,
      aboutACurrentMedication: true,
      currentMedicationOrders: [],
      statedInTheAnswer: true,
    },
    {
      type: 'interaction',
      drug: 'Lidocaine',
      detail:
        'Lidocaine interacts with active order Neomycin — Minor. Limited in vitro data suggest that some aminoglycosides may enhance the neuromuscular blocking properties of lidocaine. Data are available for neomycin only. No special precautions are necessary.',
      severity: 'Minor',
      chartOrderBridges: [],
      namedPartners: ['Neomycin'],
      restsOnAnUncorroboratedChartMatch: false,
      aboutAnEndedOrder: false,
      endedOrderStopDate: null,
      aboutACurrentMedication: true,
      currentMedicationOrders: [],
      statedInTheAnswer: true,
    },
  ],
  unstatedDosingCeilings: null,
  disclaimer:
    "This response is AI-generated and may not be accurate. It is not a substitute for clinical judgment. Always verify against the patient's medical records.",
};
